# action.yml
name: 'Phrase pull'
description: 'Pulls mindbox i18n resources from PhraseApp'
inputs:
  gitHubToken:
    description: 'Token to create pr-s'
    required: true
  phraseAppToken:
    description: 'Token to access PhraseApp'
    required: true
  baseBranch:
    description: 'Base branch for localization pull PR-s'
    required: false
    default: 'master'
  allowCyrillicSymbolsInCSharpComments:
    description: 'Allow cyrillic symbols in CSharp comments'
    required: false
    default: false
  autoMerge:
    description: Auto merge strategy. The only possible value is github
    required: false
    default: github
  commitEmail:
    description: Email for user to commit localization
    required: false
    default: 'action-ci@mindbox.ru'
  mergeMethod:
    description: Method to merge. Possible values is squash or merge
    required: false
    default: merge
runs:
  using: 'composite'
  steps:
    - run: "echo Hello"
      if: false
      shell: bash