# action.yml
name: 'Phrase pull'
description: 'Pulls mindbox i18n resources from PhraseApp'
inputs:
  gitHubToken:
    description: 'Token to create pr-s'
    required: true
  phraseAppToken:
    description: 'Token to access PhraseApp'
    required: true
  baseBranch:
    description: 'Base branch for localization pull PR's'
    required: false
    default: master

runs:
  using: 'docker'
  image: 'docker://mindboxmoscow/phrase-integration-gha'
  args:
   - pull
  env:
    gitHubToken: ${{ inputs.gitHubToken }}
    phraseAppToken: ${{ inputs.phraseAppToken }}
    baseBranch: ${{ inputs.baseBranch }}
