name: Cleanup trigger after branch deleted

on:
  delete

jobs:
  cleanup:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:

      - name: Checkout frontend-deploy repository
        uses: actions/checkout@v2
        with:
          repository: mindbox-moscow/frontend-deploy
          token: ${{ secrets.GH_FULL_TOKEN }}
          path: ./hot_build

      - name: Set variables
        run: |
          echo "ref_name=$(cat $GITHUB_EVENT_PATH | jq '.ref' | sed 's/refs\/heads\///g' | sed 's/\"//g' | sed 's/[_.\/#]/-/g' | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
        id: set_variables

      - name: Get branch and repo names hash
        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
        id: branch_and_repo_hash
        env:
          BRANCH_AND_REPO: "${{ env.repository_name }}-${{ env.ref_name }}"

      - name: Install YC
        run: |
          sudo curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          sudo ln -s /home/runner/yandex-cloud/bin/yc /bin/yc

      - name: Remove Docker Image
        run: |
          yc config profile create cleaner
          echo '${{ secrets.CONTAINER_REGISTRY_KEY }}' >> iam_key.json | yc config set service-account-key iam_key.json
          rm iam_key.json
          ./scripts/cleaner.sh $(yc iam create-token) ${{ env.ref_name }}
        working-directory: ./hot_build/hot-testing

      - name: Set variables in deployment.yml
        run: sed -i "s~HASH_PAYLOAD~$HASH_PAYLOAD~g" ./kubernetes/deploy.yml
        env:
          HASH_PAYLOAD: ${{ env.hash_payload }}
        working-directory: ./hot_build/hot-testing

      - name: Cleanup cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
            # Config file generated by this manual
            # https://cloud.yandex.ru/docs/managed-kubernetes/operations/create-static-conf
          KUBE_CONFIG_DATA: ${{ secrets.DEV_FRONTEND_GHA_KUBE_CONFIG_DATA }}
        with:
          args: kubectl delete -f ./hot_build/hot-testing/kubernetes/deploy.yml
