name: phrase_pull

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:

  phrase_pull:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      COMMAND: pull
      gitHubToken: ${{ secrets.GH_FULL_TOKEN }}
      phraseAppToken: ${{ secrets.PHRASE_TOKEN }}
      slackWebhookUrl: https://hooks.slack.com/services/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

    steps:
    - uses: actions/checkout@v1

    - name: phrase push
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: push
        gitHubToken: ${{ secrets.GH_FULL_TOKEN }}
        phraseAppToken: ${{ secrets.PHRASE_TOKEN }}
        slackWebhookUrl: https://hooks.slack.com/services/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

    - name: phrase pull
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: pull
        gitHubToken: ${{ secrets.GH_FULL_TOKEN }}
        phraseAppToken: ${{ secrets.PHRASE_TOKEN }}
        slackWebhookUrl: https://hooks.slack.com/services/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
