name: 'Create Octopus Release'
description: 'Create Release for Octopus'
inputs:
  mode:
    description: 'Mode: check/release'
    required: false
    default: 'release'
  space:
    description: 'Space in Octopus'
    required: false
    default: 'Spaces-1'
  project:
    description: 'Project'
    required: true
  env:
    description: 'Project Env'
    required: false
  release-number:
    description: 'Release Number from GitHub'
    required: true
  octopus-server:
    description: 'Octopus Server Url'
    required: true
  octopus-api-key:
    description: 'Octopus Api Key'
    required: true
  additional_params_values:
    description: 'Additional Parameters and Values for Creating Release'
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@master
      with:
        name: release-notes-artifact

    - name: "Check release notes existence"
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "releasenotes.txt"

    - name: Create Release Notes File
      if: steps.check_files.outputs.files_exists != 'true'
      uses: mindbox-moscow/github-actions/create-release-notes@lysychenko/create-release-octopus
      with:
        release-number: "${{ inputs.release-number }}"

    - name: "Create ${{ inputs.project }} Octopus Release"
      if: ${{ inputs.mode == 'release' }}
      uses: docker://octopusdeploy/octo
      with:
        args: >
          create-release
          --server ${{ inputs.octopus-server }}
          --project "${{ inputs.project }}"
          --apikey ${{ inputs.octopus-api-key }}
          --version ${{ inputs.release-number }}
          --releaseNoteFile releasenotes.txt
          --packageVersion ${{ inputs.release-number }}
          --channel Default

    - name: "Create ${{ inputs.project }} Octopus Helm Diff"
      if: ${{ inputs.mode == 'check' }}
      uses: docker://octopusdeploy/octo
      with:
        args: >
          create-release
          --server ${{ inputs.octopus-server }}
          --project "${{ inputs.project }}"
          --apikey ${{ inputs.octopus-api-key }}
          --version "${{ inputs.release-number }}"
          --releaseNoteFile releasenotes.txt
          --package "*:*:${{ inputs.release-number }}"
          --deployTo "${{ inputs.env }}"
          --waitForDeployment
          --cancelOnTimeout
          --deploymentTimeout "00:20:00"
          --progress
          ${{ inputs.additional_params_values }}
