name: 'Create Release'
description: 'Create Release for Octopus'
inputs:
  mode:
    description: 'Mode: check/release'
    required: false
    default: 'release'
  space:
    description: 'Space in Octopus'
    required: false
    default: 'Spaces-1'
  project:
    description: 'Project'
    required: true
  env:
    description: 'Project Env'
    required: false
  release-number:
    description: 'Release Number from GitHub'
    required: true
  octopus-server:
    description: 'Octopus Server'
    required: true
  octopus-api-key:
    description: 'Octopus Api Key'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
  github-repository:
    description: 'GitHub Repository'
    required: true
  github-sha:
    description: 'Current Commit'
    required: true
  additional_params_values:
    description: 'Additional Parameters and Values for Creating Release'
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "call action"
      id: last_release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ inputs.github-token }}
        exclude_types: "prerelease|draft"
        view_top: 1

    - name: "Print result"
      run: |
        echo "id: ${{ steps.last_release.outputs.id }}"
        echo "name: ${{ steps.last_release.outputs.name }}"
        echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
        echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
        echo "draft: ${{ steps.last_release.outputs.draft }}"
        echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
      shell: bash

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.9

    - name: Last release (check mode)
      if: ${{ inputs.mode == 'check' }}
      id: last_releases_octopus_check_mode
      run: >
        echo "::set-output name=last_release_version::$(
        octo list-latestdeployments 
        --project='${{ inputs.project }}' 
        --environment=${{ inputs.env }} 
        --server=${{ inputs.octopus-server }} 
        --apiKey=${{ inputs.octopus-api-key }} --space=${{ inputs.space }} | 
        grep -o 'Version:.*' | awk '{ print $2 }')"
      shell: bash
    
    - name: Last release
      if: ${{ inputs.mode == 'release' }}
      id: last_releases_octopus
      run: >
        echo "::set-output name=last_release_version::$(
        octo list-latestdeployments 
        --project='${{ inputs.project }}' 
        --server=${{ inputs.octopus-server }} 
        --apiKey=${{ inputs.octopus-api-key }} --space=${{ inputs.space }} | 
        grep -o 'Version:.*' | awk '{ print $2 }')"
      shell: bash

    - name: Create Release Notes File
      env:
        LAST_RELEASE_VERSION: "${{ inputs.mode == 'release' && steps.last_releases_octopus.outputs.last_release_version || steps.last_releases_octopus_check_mode.outputs.last_release_version }}"
      run: |
        $global:github_repository="${{ inputs.github-repository }}"
        $global:github_token="${{ inputs.github-token }}"
        $global:current_commitId="${{ inputs.github-sha }}"
        $global:last_release_version="${{ env.LAST_RELEASE_VERSION }}"
        $global:release_version="${{ inputs.release-number }}"
        ${{ github.action_path }}/release-gen.ps1
      shell: pwsh

    - name: "Create ${{ inputs.project }} Octopus Release"
      if: ${{ inputs.mode == 'release' }}
      uses: docker://octopusdeploy/octo
      with:
        args: >
          create-release
          --server ${{ inputs.octopus-server }}
          --project "${{ inputs.project }}"
          --version ${{ inputs.release-number }}
          --packageVersion ${{ inputs.release-number }}
          --channel Default
          --apikey ${{ inputs.octopus-api-key }}
          --releaseNoteFile releasenotes.txt

    - name: "Create ${{ inputs.project }} Octopus Helm Diff"
      if: ${{ inputs.mode == 'check' }}
      uses: docker://octopusdeploy/octo
      with:
        args: >
          create-release
          --server ${{ inputs.octopus-server }}
          --project "${{ inputs.project }}"
          --apikey ${{ inputs.octopus-api-key }}
          --package "*:*:${{ inputs.release-number }}"
          --deployTo "${{ inputs.env }}"
          --waitForDeployment
          --version "${{ inputs.release-number }}"
          --cancelOnTimeout
          --deploymentTimeout "00:20:00"
          --releaseNoteFile releasenotes.txt 
          --progress
          ${{ inputs.additional_params_values }}