name: GraphQL Inspector
description: 'Verify graphql schema can be merged'

inputs:
  oldSchemaFile:
    description: 'Current schema file to validate against.'
    required: true
  newSchemaFile:
    description: 'New schema file to be validated.'
    required: true

outputs: {}

runs:
  using: 'composite'
  steps:

    - name: Check new schema presence
      id: new_schema_presence
      uses: andstor/file-existence-action@v3
      with:
        files: ${{ inputs.newSchemaFile }}

    - name: Fail with missing new schema
      if: steps.new_schema_presence.outputs.files_exists == 'false'
      shell: bash
      run: exit 1

    - name: Copy new schema to old schema place
      shell: bash
      run: cp -f ${{ inputs.newSchemaFile }} ${{ inputs.oldSchemaFile }}

    - name: Commit new schema
      uses: EndBug/add-and-commit@v9
      with:
        add: ${{ inputs.oldSchemaFile }}
        message: Commit updated ${{ inputs.oldSchemaFile }}
        committer_name: GitHub Actions
        committer_email: actions@github.com
