name: 'Create Release'
description: 'Create Release'
inputs:
  release-number:
    description: 'Release number'
    required: true
    default: 'empty'
  prerelease:
    description: 'If prerelease - true, else false'
    required: false
    default: false
outputs:
  release-number: 
    description: "Release number"
    value: ${{ inputs.release-number != 'empty' && inputs.release-number || steps.release-number.outputs.release-number }}
  release-notes-body: 
    description: "Body for Release Notes"
    value: "[View release in GitHub](${{ steps.create_release.outputs.html_url }})  /\${{ steps.changelog.outputs.changelog }} <br /> PLEEASE"
  release-url:
    description: "GitHub Release URL"
    value: ${{ steps.create_release.outputs.html_url }}
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: generate release number
      if: ${{ inputs.release-number == 'empty' }}
      id: release-number
      uses: mindbox-moscow/gha-release-number@v1.0.1
      with:
        token: ${{ github.token }}

    - name: Changelog
      uses: Bullrich/generate-release-changelog@master
      id: changelog
      env:
        REPO: ${{ github.repository }}

    - name: "Create GitHub Release"
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: "${{ inputs.release-number != 'empty' && inputs.release-number || steps.release-number.outputs.release-number }}"
        release_name: "Release ${{ inputs.release-number != 'empty' && inputs.release-number || steps.release-number.outputs.release-number }}"
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: ${{ inputs.prerelease }}