name: 'Create Release'
description: 'Create Release'
inputs:
  release-number:
    description: 'Release number'
    required: true
    default: 'empty'
  prerelease:
    description: 'If prerelease - true, else false'
    required: false
    default: false
  checkout:
    description: 'If it need to checkout master'
    required: false
    default: 'true'
outputs:
  release-number: 
    description: "Release number"
    value: ${{ inputs.release-number != 'empty' && inputs.release-number || steps.release-number.outputs.release-number }}
  release-notes-body: 
    description: "Body for Release Notes"
    value:  '[View release in GitHub](${{ steps.create_release.outputs.html_url }}) <br /> ${{ steps.clean-changelog.outputs.changelog }}'
  release-url:
    description: "GitHub Release URL"
    value: ${{ steps.create_release.outputs.html_url }}
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@master

    - name: generate release number
      if: ${{ inputs.release-number == 'empty' }}
      id: release-number
      uses: mindbox-cloud/gha-release-number@master
      with:
        token: ${{ github.token }}

    - name: Changelog
      uses: mindbox-cloud/github-actions/generate-release-changelog@Nikolaeva/nexus_release_problem_inspection
      id: changelog
      env:
        REPO: ${{ github.repository }}

    - name: clean changelog from quotes
      run: |
        echo "changelog=$((echo "${{ steps.changelog.outputs.changelog }}") | sed "s/\"//g" | sed "s/'//g" )" >> "$GITHUB_OUTPUT"
      id: clean-changelog
      shell: bash

    - name: "Create GitHub Release"
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: "${{ inputs.release-number != 'empty' && inputs.release-number || steps.release-number.outputs.release-number }}"
        name: "Release ${{ inputs.release-number != 'empty' && inputs.release-number || steps.release-number.outputs.release-number }}"
        body: |
          ${{ steps.clean-changelog.outputs.changelog }}
        draft: false
        prerelease: ${{ inputs.prerelease }}
