# action.yml
name: 'Phrase push'
description: 'Pushes new localization keys to PhraseApp'
inputs:
  phraseAppToken:
    description: 'Token to access PhraseApp'
    required: true

runs:
  using: 'composite'
  steps:
    - run: "echo Hello" # intentionally, phrase isn't working rn
      if: false
      shell: bash
