# action.yml
name: 'Check translation'
description: 'Checks Mindbox i18n files in .NET solution'
inputs:
  skip-inclusion-check:
    description: 'Forces checker to skip inclusion check'
    required: false
    default: false
  skip-new-cyrillic-lines-check:
    description: 'Forces checker to skip new cyrillic lines check'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'docker://mindboxmoscow/translation-checker-gha'
  env:
    skipInclusionCheck: ${{ inputs.skip-inclusion-check }}
    skip-new-cyrillic-lines-check: ${{ inputs.skip-new-cyrillic-lines-check }}