name: 'Create Release'
description: 'Create Release'
inputs:
  release-number:
    description: 'Release number'
    required: false
  prerelease:
    description: 'If prerelease - true, else release - false'
    required: false
    default: false
  project:
    description: 'Project'
    required: true
  octopus-server:
    description: 'Octopus Server Url. Better use secrets.OCTOPUS_SERVER, if exist'
    required: true
  octopus-api-key:
    description: 'Octopus Api Key. Better use secrets.OCTOPUS_API_KEY, if exist'
    required: true
  additional_params_values:
    description: 'Additional Parameters and Values for Creating Release'
    required: false
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: generate release number
      if: ${{ inputs.prerelease == 'false' }}
      id: release-number
      uses: mindbox-moscow/gha-release-number@v1.0.1
      with:
        token: ${{ github.token }}

    - name: sleep
      if: ${{ strategy.job-index != 0 }}
      run: sleep 2s
      shell: bash

    - name: "Create Github Release"
      uses: mindbox-moscow/github-actions/create-github-release@master
      with:
        release-number: "${{ inputs.prerelease && inputs.release-number || steps.release-number.outputs.release-number }}"
        prerelease: ${{ inputs.prerelease }}

    - uses: actions/download-artifact@master
      with:
        name: release-notes-artifact

    # - name: "Create ${{ inputs.project }} Octopus Release"
    #   uses: docker://octopusdeploy/octo
    #   with:
    #     args: >
    #       create-release
    #       --server ${{ inputs.octopus-server }}
    #       --project "${{ inputs.project }}"
    #       --apikey ${{ inputs.octopus-api-key }}
    #       --version "${{ inputs.prerelease && inputs.release-number || steps.release-number.outputs.release-number }}"
    #       --packageVersion "${{ inputs.prerelease && inputs.release-number || steps.release-number.outputs.release-number }}"
    #       --releaseNoteFile releasenotes.txt
    #       ${{ inputs.additional_params_values }}

    