name: 'Create Release'
description: 'Create Release'
inputs:
  release-number:
    description: 'Release number'
    required: true
  prerelease:
    description: 'If prerelease - true, else release - false'
    required: false
    default: false
  project:
    description: 'Project'
    required: true
  octopus-server:
    description: 'Octopus Server Url. Better use secrets.OCTOPUS_SERVER, if exist'
    required: true
  octopus-api-key:
    description: 'Octopus Api Key. Better use secrets.OCTOPUS_API_KEY, if exist'
    required: true
  additional_params_values:
    description: 'Additional Parameters and Values for Creating Release'
    required: false
runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@master
    
    - name: "Create Github Release"
      uses: mindbox-moscow/github-actions/create-github-release@lysychenko/create-release
      with:
        release-number: ${{ inputs.release-number }}
        prerelease: ${{ inputs.prerelease }}

    - uses: actions/download-artifact@master
      with:
        name: release-notes-artifact

    - name: "Create ${{ inputs.project }} Octopus Release"
      uses: docker://octopusdeploy/octo
      with:
        args: >
          create-release
          --server ${{ inputs.octopus-server }}
          --project "${{ inputs.project }}"
          --apikey ${{ inputs.octopus-api-key }}
          --version "${{ inputs.release-number }}"
          --releaseNoteFile releasenotes.txt
          ${{ inputs.additional_params_values }}

    