name: Helmfile validate
description: Validates helmfile releases
inputs:
  path:
    description: Path to helmfile.yaml
    required: false
    default: helmfile/helmfile.yaml
  environment:
    description: Helmfile environment
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.0.0

    - name: Helmfile lint
      run: helmfile -f ${{ inputs.path }} --environment ${{ inputs.environment }} lint --args "--strict --quiet"

    - name: Helmfile template
      run: helmfile -f ${{ inputs.path }} --environment ${{ inputs.environment }} template
