name: 'Kyverno K8s policies'
description: 'Action to check K8s manifests to consist policies'
inputs:
  kyvernoPolicies:
    description: ''
    required: true
  validatedResource:
    description: ''
    required: true
  mindboxOrgGithubToken:
    description: 'Used to download organization wide resources, like terraform-modules repo'
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Download Kyverno policies"
      uses: actions/checkout@master
      with:
        repository: mindbox-moscow/kubernetes-system-layer

    - name: Validate policies
      uses: gbaeke/kyverno-cli@v1
      with:
        command: |
          kyverno apply kubernetes-system-layer/charts/kyverno-extend/templates --resource=${{ inputs.validatedResource }} --v 3
