name: 'Kyverno K8s policies'
description: 'Action to check K8s manifests to consist policies'
inputs:
  kyvernoPolicies:
    description: ''
    required: true
  validatedResource:
    description: ''
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1.0.0
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.0.0
      with:
        kubectl-version: "v1.21.11"
        helm-version: "v3.8.2"
        helmfile-version: "v0.143.0"

    - name: Test
      shell: bash
      run: |
        helmfile --version
        helm version
        kubectl version --client

    - name: Prepare K8s manifests
      shell: bash
      run: |
        cd ${{ inputs.validatedResource }}
        helmfile template > test.yaml

    - name: Validate policies
      uses: gbaeke/kyverno-cli@v1
      with:
        command: |
          kyverno apply ${{ inputs.kyvernoPolicies }} --resource=test.yaml
