name: 'Kyverno K8s policies'
description: 'Action to check K8s manifests to consist policies'
inputs:
  validatedResource:
    description: ''
    required: true
  verboseLevel:
    description: ''
    required: false
    default: '1'
  mindboxOrgGithubToken:
    description: 'Used to download organization wide resources, like terraform-modules repo'
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Clone repo with Kyverno policies"
      uses: actions/checkout@v2
      with:
        repository: mindbox-moscow/kubernetes-system-layer.git
        token: ${{ inputs.mindboxOrgGithubToken }}
        path: kubernetes-system-layer
        ref: master

    - name: Validate policies
      uses: gbaeke/kyverno-cli@v1
      with:
        command: |
          kyverno apply kubernetes-system-layer/charts/kyverno-extend/templates --resource=${{ inputs.validatedResource }} --v ${{ inputs.verboseLevel }}
