name: 'Composite Terraform'
description: 'Composite Terraform GitHub Actions'
inputs:
  terraformVersion:
    description: ''
    required: true
  githubToken: 
    description: ''
    required: true
  mindboxOrgGithubToken:
    description: 'Used to download organization wide resources, like terraform-modules repo'
    required: true
  workingDir:
    description: ''
    required: true
  tfBackendAccessKey:
    description: ''
    required: true
  tfBackendSecretKey:
    description: ''
    required: true
  servicePrincipalClientSecret:
    description: ''
    required: true
  armClientId:
    description: ''
    required: true
  armTenantId:
    description: ''
    required: true
  armSubscriptionId:
    description: ''
    required: true
  planAdditionalVars:
    description: ''
    required: false
    default: ''
outputs: {}
runs:
  using: "composite"
  steps:
    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: ${{ inputs.terraformVersion }}
          terraform_wrapper: false

    - name: "Terraform Format"
      id: fmt
      run: terraform fmt
      # continue-on-error: true
      working-directory: ${{ inputs.workingDir }}
      shell: bash

    - name: "Setup github token for module repo"
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://octopus-mindbox:${OCTOPUS_MINDBOX_GITHUB_TOKEN}@github.com/mindbox-moscow".insteadOf "https://github.com/mindbox-moscow"
      env:
        OCTOPUS_MINDBOX_GITHUB_TOKEN: ${{ inputs.mindboxOrgGithubToken }}
      working-directory: ${{ inputs.workingDir }}
      shell: bash

    - name: "Terraform Init"
      id: init
      run: terraform init
        -backend-config="access_key=${{ inputs.tfBackendAccessKey }}"
        -backend-config="secret_key=${{ inputs.tfBackendSecretKey }}"
      working-directory: ${{ inputs.workingDir }}
      shell: bash

    - name: "Terraform Validate"
      id: validate
      run: terraform validate -no-color
      working-directory: ${{ inputs.workingDir }}
      shell: bash

    - name: "Terraform Plan"
      id: plan
      run: |
        set +e
        PLAN="terraform plan ${{ inputs.planAdditionalVars }}  -no-color -out=plan.tfplan -detailed-exitcode"
        $PLAN
        echo "::set-output name=planExitCode::$?"
        exit 0
      env:
        ARM_CLIENT_ID: ${{ inputs.armClientId }}
        ARM_TENANT_ID: ${{ inputs.armTenantId }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.armSubscriptionId }}
        ARM_CLIENT_SECRET: "${{ inputs.servicePrincipalClientSecret }}"
      working-directory: ${{ inputs.workingDir }}
      # continue-on-error: true
      shell: bash

    - name: "Fail if plan failed"
      id: failIfPlanFailed
      run: |
        echo "planExitCode is: ${{ steps.plan.outputs.planExitCode }}"
        set -x
        if [[ ${{ steps.plan.outputs.planExitCode }} -eq 1 ]]; then
          exit 1
        fi
      working-directory: ${{ inputs.workingDir }}
      shell: bash

    # - name: "Setup Terraform"
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #       terraform_version: ${{ inputs.terraformVersion }}
    
    - name: "Terraform Show"
      id: show
      run: |
        if [ ${{ steps.plan.outputs.planExitCode }} -ne 0]; then
          terraform show -no-color plan.tfplan
        fi
      working-directory: ${{ inputs.workingDir }}
      shell: bash

    - uses: actions/github-script@0.9.0
      name: "Comment plan"
      env:
        PLAN: "${{ steps.show.outputs.stdout }}"
        CONDITION: "${{ steps.plan.outputs.planExitCode }}"
      with:
        github-token: ${{ inputs.githubToken }}
        script: |
          if (process.env.CONDITION == "2") {
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`Success with non-empty diff\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.workingDir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
