name: 'generate-release-changelog'
description: 'GitHub Action for generating a changelog of all commits in a release'
author: 'Javier Bullrich'
outputs:
  changelog:
    description: 'Generate changelog'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'edit'
  color: 'gray-dark'
