name: phrase_pull

on:
  workflow_call:
    secrets:
      phrase_app_token:
        description: 'A PHRASE_TOKEN token passed from the caller workflow'
        required: true
      slack_webhook_url:
        description: 'A SLACK_WEBHOOK_TO_NEW_TRANSLATIONS token passed from the caller workflow'
        required: true
      frontend_gha_full_token:
        description: 'A FRONTEND_GHA_FULL_TOKEN token passed from the caller workflow'
        required: true

jobs:

  phrase_pull:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      COMMAND: pull
      gitHubToken: ${{ secrets.frontend_gha_full_token }}
      phraseAppToken: ${{ secrets.phrase_app_token }}
      slackWebhookUrl: ${{ secrets.slack_webhook_url }}

    steps:
    - uses: actions/checkout@v1

    - name: phrase push
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: push
        gitHubToken: ${{ secrets.frontend_gha_full_token }}
        phraseAppToken: ${{ secrets.phrase_app_token }}
        slackWebhookUrl: ${{ secrets.slack_webhook_url }}

    - name: phrase pull
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: pull
        gitHubToken: ${{ secrets.frontend_gha_full_token }}
        phraseAppToken: ${{ secrets.phrase_app_token }}
        slackWebhookUrl: ${{ secrets.slack_webhook_url }}
