name: e2e tests

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node.js version"
        default: "18.18.2"
        required: false
        type: string
      e2e-timeout:
        description: "Timeout in minutes"
        default: 20
        required: false
        type: number
      retries:
        description: "Number of retries"
        default: 2
        required: false
        type: number
      registry_id:
        description: "YC registry ID"
        default: "crpo9tj76o3c7pi8i72n"
        required: false
        type: string
      image_name:
        description: "Hot-testing image name"
        default: "e2e_new_frontend"
        required: false
        type: string
      template_bucket:
        description: "Bucket with actual statics"
        default: "mindbox-newfrontend-templates"
        required: false
        type: string
      template_folder:
        description: "Folder in bucket with actual statics"
        default: "microapps"
        required: false
        type: string
      core_project:
        description: "True if project is frontend_core_v2"
        default: false
        required: false
        type: boolean
      use_k8_deploy_process:
        type: boolean
        description: "True if need to use new deployment procedure"
        required: false
        default: true
      target_port:
        type: number
        description: "The port for k8 services"
        required: false
        default: 8080
    secrets:
      npm_token:
        description: "A GH_NPM_REGISTRY token passed from the caller workflow"
        required: true
      frontend_gha_full_token:
        description: "A FRONTEND_GHA_FULL_TOKEN token passed from the caller workflow"
        required: true
      kube_dev_config:
        description: "A DEV_FRONTEND_GHA_KUBE_CONFIG_DATA token passed from the caller workflow"
        required: true
      container_registry_key:
        description: "A CONTAINER_REGISTRY_KEY token passed from the caller workflow"
        required: true
      bucket_access_id:
        description: "A NEW_FRONTEND_STAGING_TEMPLATE_BUCKET_KEY_ID token passed from the caller workflow"
        required: true
      bucket_access_key:
        description: "A NEW_FRONTEND_STAGING_TEMPLATE_BUCKET_ACCESS_KEY token passed from the caller workflow"
        required: true
      cypress_login:
        description: "A CYPRESS_LOGIN token passed from the caller workflow"
        required: true
      cypress_pass:
        description: "A CYPRESS_PASSWORD token passed from the caller workflow"
        required: true
      kube_dev_config_k8:
        description: "A SA_TOKEN_DTLN_KUBE_CDP_STAGING_MICROFRONTENDS token passed from the caller workflow for new deploy"
        required: false

env:
  NODE_OPTIONS: --unhandled-rejections=strict

jobs:
  prepare-site:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.head_ref, 'LocalizationPull') }}
    env:
      retries: ${{ inputs.retries }}
      CYPRESS_username: "${{ secrets.cypress_login }}"
      CYPRESS_password: "${{ secrets.cypress_pass }}"
      registry: cr.yandex/${{ inputs.registry_id }}
      image: ${{ inputs.image_name }}
      template_bucket: ${{ inputs.template_bucket }}
      template_folder: ${{ inputs.template_folder }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Change Dockerd param
        run: |
          sudo sed -i 's/ }/, \"max-concurrent-uploads\": 2 }/' /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Set variables
        run: |
          echo "ref_name=$(echo $GITHUB_HEAD_REF | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
        id: set_variables

      - name: Get branch and repo names hash
        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
        id: branch_and_repo_hash
        env:
          BRANCH_AND_REPO: "${{ env.repository_name }} ${{ env.ref_name }}"

      - name: Set project path
        run: |
          project_name=$(cat ./package.json | jq .name | sed -s 's/@mindbox-cloud\///g' | sed -s 's/-/_/g' | sed -s 's/"//g')
          if [[ $project_name == "frontend_core_v2" ]]; then
            echo "project_folder=core" >> $GITHUB_ENV
            echo "project_name=core" >> $GITHUB_ENV
            echo "frontend_core_service=e2e-testing-${{ env.hash_payload }}" >> $GITHUB_ENV
          else
            echo "project_folder=$project_name" >> $GITHUB_ENV
            echo "project_name=$project_name" >> $GITHUB_ENV
            echo "frontend_core_service=core-service-standard" >> $GITHUB_ENV
          fi
        id: set_project

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node_version }}
          registry-url: "https://npm.pkg.github.com/mindbox-cloud"

      - name: Get node modules from cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: npm-ci-${{ github.sha }}

      - name: Disable Lefthook
        run: echo "LEFTHOOK=0" >> $GITHUB_ENV

      - name: Authenticate in yandex registry
        run: echo '${{ secrets.container_registry_key }}' | docker login -u json_key --password-stdin cr.yandex

      - name: Checkout frontend-deploy repository
        uses: actions/checkout@v3
        with:
          repository: mindbox-cloud/frontend-deploy
          token: ${{ secrets.frontend_gha_full_token }}
          path: ./deploy

      - name: Select core deploy.yml
        if: ${{ env.repository_name == 'frontend-core-v2' }}
        run: mv ./deploy/e2e/kubernetes/deploy-k8-core.yml ./deploy/e2e/kubernetes/deploy-k8.yml

      - name: Select micro deploy.yml
        if: ${{ env.repository_name != 'frontend-core-v2' }}
        run: mv ./deploy/e2e/kubernetes/deploy-k8-micro.yml ./deploy/e2e/kubernetes/deploy-k8.yml

      - name: Build and format npm-package for new deploy

        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          MCF_STATIC_FOLDER: v2_static

      # needed for frontend discovery(build initial.js)
      - name: copy remoteEntry to v2_static folder
        run: |
          find . -type f -name "remoteEntry.js" -exec cp {} ./v2_static/ \;
        working-directory: ./build

      - name: Copy Dockerfile to build folder
        run: |
          cp ./deploy/mcf-release/Dockerfile ./build
          cp ./deploy/mcf-release/nginx.conf ./build

      - name: Build docker image
        working-directory: ./build
        run: |
          docker build . -t ${{ env.registry }}/${{ env.image }}-k8/${{ env.ref_name }}:${{ github.sha }}

      - name: Push docker image
        run: docker push ${{ env.registry }}/${{ env.image }}-k8/${{ env.ref_name }}:${{ github.sha }}

      - name: Set variables in deployment.yaml
        working-directory: ./deploy/e2e/kubernetes
        run: |
          sed -i "s~DOCKER_IMAGE~$DOCKER_IMAGE~g" ./deploy-k8.yml
          sed -i "s~HASH_PAYLOAD~$HASH_PAYLOAD~g" ./deploy-k8.yml
          sed -i "s~CI_COMMIT_SHA~$CI_COMMIT_SHA~g" ./deploy-k8.yml
          sed -i "s~BASE_PROJECT_URL~$BASE_PROJECT_URL~g" ./deploy-k8.yml
          sed -i "s~PROJECT_FOLDER~$PROJECT_FOLDER~g" ./deploy-k8.yml
          sed -i "s~TARGET_PORT~$TARGET_PORT~g" ./deploy-k8.yml
          sed -i "s~FRONTEND_CORE_SERVICE_NAME~$FRONTEND_CORE_SERVICE_NAME~g" ./deploy-k8.yml
        env:
          DOCKER_IMAGE: ${{ env.registry }}/${{ env.image }}-k8/${{ env.ref_name }}:${{ github.sha }}
          HASH_PAYLOAD: ${{ env.hash_payload }}
          CI_COMMIT_SHA: ${{ github.sha }}
          BASE_PROJECT_URL: standard.mindbox.ru
          PROJECT_FOLDER: ${{ env.project_folder }}
          TARGET_PORT: ${{ inputs.target_port }}
          FRONTEND_CORE_SERVICE_NAME: ${{ env.frontend_core_service }}

      - name: Deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          # Config file generated by this manual
          # https://cloud.yandex.ru/docs/managed-kubernetes/operations/create-static-conf
          KUBE_CONFIG_DATA: ${{ secrets.kube_dev_config_k8 }}
        with:
          args: kubectl apply -f ./deploy/e2e/kubernetes/deploy-k8.yml

      - name: Check dns record creation
        id: check_dns
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 15
          shell: bash
          max_attempts: 40
          retry_wait_seconds: 5
          command: dig -t cname +short e2e-testing-${{ env.hash_payload }}-staging.mindbox.ru. | grep -q "mindbox-cdp.trafficmanager.net." || exit 1
        continue-on-error: true

      - name: Fail with error message
        if: ${{ steps.check_dns.outcome == 'failure' }}
        run: |
          echo "The DNS CNAME record for 'e2e-testing-${{ env.hash_payload }}-staging.mindbox.ru' was not created as expected."
          exit 1

  e2e-tests:
    runs-on: [self-hosted, frontend]
    container:
      image: cypress/browsers:node-18.16.0-chrome-112.0.5615.121-1-ff-112.0.1-edge-112.0.1722.48-1
      volumes:
        - /runner/.cache/Cypress:/root/.cache/Cypress
    needs: prepare-site
    timeout-minutes: ${{ inputs.e2e-timeout }}
    if: ${{ always() && !cancelled() && !contains(github.head_ref, 'LocalizationPull') && !inputs.core_project }}
    env:
      retries: ${{ inputs.retries }}
      CYPRESS_username: "${{ secrets.cypress_login }}"
      CYPRESS_password: "${{ secrets.cypress_pass }}"
      registry: cr.yandex/${{ inputs.registry_id }}
      image: ${{ inputs.image_name }}
      template_bucket: ${{ inputs.template_bucket }}
      template_folder: ${{ inputs.template_folder }}

    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: check fail
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: echo "previous steps are failed" && exit 1

      - name: install additional tools
        run: apt-get update && apt-get -y install jq

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          echo "ref_name=$(echo $GITHUB_HEAD_REF | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
        id: set_variables

      - name: Get branch and repo names hash
        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
        id: branch_and_repo_hash
        env:
          BRANCH_AND_REPO: "${{ env.repository_name }} ${{ env.ref_name }}"

      - name: Set project path
        run: |
          project_name=$(cat ./package.json | jq .name | sed -s 's/@mindbox-cloud\///g' | sed -s 's/-/_/g' | sed -s 's/"//g')
          if [[ $project_name == "frontend_core_v2" ]]; then
            echo "project_folder=core" >> $GITHUB_ENV
            echo "project_name=core" >> $GITHUB_ENV
          else
            echo "project_folder=$project_name" >> $GITHUB_ENV
            echo "project_name=$project_name" >> $GITHUB_ENV
          fi
        id: set_project

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node_version }}
          registry-url: "https://npm.pkg.github.com/mindbox-cloud"

      - name: Run E2E tests on not core project (v5).
        uses: cypress-io/github-action@v5
        with:
          install: true
          config: baseUrl=https://e2e-testing-${{ env.hash_payload }}-staging.mindbox.ru,retries=${{ env.retries }},videoUploadOnPasses=false,videoCompression=false
          working-directory: e2e
          browser: chrome
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: Upload test results artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-${{ env.project_name }}
          path: e2e/cypress
          retention-days: 1

  core-e2e-tests-matrix:
    runs-on: ubuntu-latest
    needs: prepare-site
    if: ${{ !contains(github.head_ref, 'LocalizationPull') && inputs.core_project }}
    env:
      retries: ${{ inputs.retries }}
      CYPRESS_username: "${{ secrets.cypress_login }}"
      CYPRESS_password: "${{ secrets.cypress_pass }}"
      registry: cr.yandex/${{ inputs.registry_id }}
      image: ${{ inputs.image_name }}
      template_bucket: ${{ inputs.template_bucket }}
      template_folder: ${{ inputs.template_folder }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          echo "ref_name=$(echo $GITHUB_HEAD_REF | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
        id: set_variables

      - name: Get branch and repo names hash
        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
        id: branch_and_repo_hash
        env:
          BRANCH_AND_REPO: "${{ env.repository_name }} ${{ env.ref_name }}"

      - name: Set project path
        run: |
          project_name=$(cat ./package.json | jq .name | sed -s 's/@mindbox-cloud\///g' | sed -s 's/-/_/g' | sed -s 's/"//g')
          if [[ $project_name == "frontend_core_v2" ]]; then
            echo "project_folder=core" >> $GITHUB_ENV
            echo "project_name=core" >> $GITHUB_ENV
          else
            echo "project_folder=$project_name" >> $GITHUB_ENV
            echo "project_name=$project_name" >> $GITHUB_ENV
          fi
        id: set_project

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node_version }}
          registry-url: "https://npm.pkg.github.com/mindbox-cloud"

      - name: Install YC
        run: |
          sudo curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          sudo ln -s /home/runner/yandex-cloud/bin/yc /bin/yc

      - name: Create e2e tests list
        id: set-matrix
        run: |
          yc config profile create frontend-ci
          echo '${{ secrets.container_registry_key }}' >> iam_key.json | yc config set service-account-key iam_key.json
          rm iam_key.json
          project_matrix=$(curl -s -H "Authorization: Bearer $(yc iam create-token)" $URL?repositoryName=${{ inputs.registry_id }}/frontend-e2e\&pageSize\=1000 | jq -r ".images[].tags[]?" | sed 's/-latest//g' | jq -R . | jq -s -c .)
          echo "matrix=$project_matrix" >> $GITHUB_OUTPUT
        env:
          URL: "https://container-registry.api.cloud.yandex.net/container-registry/v1/images"

  core-e2e-tests-runner:
    runs-on: [self-hosted, frontend]
    needs: core-e2e-tests-matrix
    strategy:
      matrix:
        project: ${{ fromJSON(needs.core-e2e-tests-matrix.outputs.matrix) }}
      max-parallel: 4
    timeout-minutes: ${{ inputs.e2e-timeout }}
    if: ${{ always() && !cancelled() && !contains(github.head_ref, 'LocalizationPull') && inputs.core_project }}
    env:
      retries: ${{ inputs.retries }}
      CYPRESS_username: "${{ secrets.cypress_login }}"
      CYPRESS_password: "${{ secrets.cypress_pass }}"
      registry: cr.yandex/${{ inputs.registry_id }}
      image: ${{ inputs.image_name }}
      template_bucket: ${{ inputs.template_bucket }}
      template_folder: ${{ inputs.template_folder }}

    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: check fail
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: echo "previous steps are failed" && exit 1

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          echo "ref_name=$(echo $GITHUB_HEAD_REF | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
        id: set_variables

      - name: Get branch and repo names hash
        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
        id: branch_and_repo_hash
        env:
          BRANCH_AND_REPO: "${{ env.repository_name }} ${{ env.ref_name }}"

      - name: Set project path
        run: |
          project_name=$(cat ./package.json | jq .name | sed -s 's/@mindbox-cloud\///g' | sed -s 's/-/_/g' | sed -s 's/"//g')
          if [[ $project_name == "frontend_core_v2" ]]; then
            echo "project_folder=core" >> $GITHUB_ENV
            echo "project_name=core" >> $GITHUB_ENV
          else
            echo "project_folder=$project_name" >> $GITHUB_ENV
            echo "project_name=$project_name" >> $GITHUB_ENV
          fi
        id: set_project

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node_version }}
          registry-url: "https://npm.pkg.github.com/mindbox-cloud"

      - name: Authenticate in yandex registry
        run: echo '${{ secrets.container_registry_key }}' | docker login -u json_key --password-stdin cr.yandex

      - name: Run E2E tests on core project.
        run: |
          [ -d ./cypress/${{ matrix.project }} ] && mkdir -p ./cypress/${{ matrix.project }}
          mkdir -p ./cypress/${{ matrix.project }}/videos && mkdir -p ./cypress/${{ matrix.project }}/screenshots
          docker run -i \
            --pull always \
            -e BASE_URL="${{ env.E2E_URL }}" \
            -e RETRIES="${{ env.retries }}" \
            -e CYPRESS_username=${{ secrets.cypress_login }} \
            -e CYPRESS_password=${{ secrets.cypress_pass }} \
            -e CYPRESS_grepTags="@smoke" \
            -e CYPRESS_grepOmitFiltered=true \
            -v $(pwd)/cypress/${{ matrix.project }}/videos:/e2e/cypress/videos \
            -v $(pwd)/cypress/${{ matrix.project }}/screenshots:/e2e/cypress/screenshots \
            cr.yandex/${{ inputs.registry_id }}/frontend-e2e:${{ matrix.project }}-latest 2>&1
        env:
          E2E_URL: https://e2e-testing-${{ env.hash_payload }}-staging.mindbox.ru

      - name: Upload test results artifacts
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cypress-${{ matrix.project }}
          path: e2e/cypress
          retention-days: 1

  post-e2e-tests:
    runs-on: ubuntu-latest
    needs: [e2e-tests, core-e2e-tests-runner]
    if: ${{ failure() }}
    steps:
      - name: Add comment to commit if the job has failed
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v2
        with:
          message: ":negative_squared_cross_mark: E2E tests failed. Check logs at\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  clean-up-e2e-tests:
    needs: [e2e-tests, core-e2e-tests-runner]
    if: ${{ always() && ( needs.e2e-tests.result == 'success' || needs.core-e2e-tests-runner.result == 'success' ) }}
    uses: mindbox-cloud/github-actions/.github/workflows/frontend_cleanup_testing.yml@master
    with:
      hot_testing: false
      hot_testing_k8: false
      e2e_testing: true
      e2e_testing_k8: true
    secrets:
      frontend_gha_full_token: ${{ secrets.frontend_gha_full_token }}
      kube_dev_config: "nothing here"
      container_registry_key: ${{ secrets.container_registry_key }}
      kube_dev_config_k8: ${{ secrets.kube_dev_config_k8 }}
