name: phrase_push

on:
  workflow_call:
    secrets:
      phrase_app_token:
        description: 'A PHRASE_TOKEN token passed from the caller workflow'
        required: true
      slack_webhook_url:
        description: 'A SLACK_WEBHOOK_TO_NEW_TRANSLATIONS token passed from the caller workflow'
        required: true
jobs:
  phrase_push:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    env:
      COMMAND: push
      gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      phraseAppToken: ${{ secrets.phrase_app_token }}
      slackWebhookUrl: ${{ secrets.slack_webhook_url }}

    steps:
    - uses: actions/checkout@v2

    - name: phrase push
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: push
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        phraseAppToken: ${{ secrets.phrase_app_token }}
        slackWebhookUrl: ${{ secrets.slack_webhook_url }}
