name: phrase_pull

on:
  workflow_call:

jobs:

  phrase_pull:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      COMMAND: pull
      gitHubToken: ${{ secrets.GH_FULL_TOKEN }}
      phraseAppToken: ${{ secrets.PHRASE_TOKEN }}
      slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_TO_NEW_TRANSLATIONS }}

    steps:
    - uses: actions/checkout@v1

    - name: phrase push
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: push
        gitHubToken: ${{ secrets.GH_FULL_TOKEN }}
        phraseAppToken: ${{ secrets.PHRASE_TOKEN }}
        slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_TO_NEW_TRANSLATIONS }}

    - name: phrase pull
      uses: mindbox-moscow/gha-phrase-integration@master
      with:
        command: pull
        gitHubToken: ${{ secrets.GH_FULL_TOKEN }}
        phraseAppToken: ${{ secrets.PHRASE_TOKEN }}
        slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_TO_NEW_TRANSLATIONS }}
