name: Deploy Hot-testing container

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node.js version"
        default: "18.x"
        required: false
        type: string
      registry_id:
        description: "YC registry ID"
        default: "crpo9tj76o3c7pi8i72n"
        required: false
        type: string
      image_name:
        description: "Hot-testing image name"
        default: "dev_new_frontend"
        required: false
        type: string
      template_bucket:
        description: "Bucket with actual statics"
        default: "mindbox-newfrontend-templates"
        required: false
        type: string
      template_folder:
        description: "Folder in bucket with actual statics"
        default: "microapps"
        required: false
        type: string
      use_k8_deploy_process:
        type: boolean
        description: "True if need to use new deployment procedure"
        required: false
        default: true
      base_project_url:
        type: string
        description: "The project which will be used for downloading all static"
        required: false
        default: test-staging.mindbox.ru
      target_port:
        type: number
        description: "The port for k8 services"
        required: false
        default: 8080
    secrets:
      npm_token:
        description: "A GH_NPM_REGISTRY token passed from the caller workflow"
        required: true
      frontend_gha_full_token:
        description: "A FRONTEND_GHA_FULL_TOKEN token passed from the caller workflow"
        required: true
      kube_dev_config:
        description: "A DEV_FRONTEND_GHA_KUBE_CONFIG_DATA token passed from the caller workflow"
        required: true
      kube_dev_config_k8:
        description: "A SA_TOKEN_DTLN_KUBE_CDP_STAGING_MICROFRONTENDS token passed from the caller workflow for new deploy"
        required: false
      container_registry_key:
        description: "A CONTAINER_REGISTRY_KEY token passed from the caller workflow"
        required: true
      slack_webhook_url:
        description: "A FRONTEND_PIPELINE_SLACK_WEBHOOK_URL token passed from the caller workflow"
        required: true
      bucket_access_id:
        description: "A NEW_FRONTEND_STAGING_TEMPLATE_BUCKET_KEY_ID token passed from the caller workflow"
        required: true
      bucket_access_key:
        description: "A NEW_FRONTEND_STAGING_TEMPLATE_BUCKET_ACCESS_KEY token passed from the caller workflow"
        required: true

jobs:
  hot-testing:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ !contains(github.head_ref, 'LocalizationPull') && github.event.pull_request.user.login != 'renovate[bot]' }}
    env:
      registry: cr.yandex/${{ inputs.registry_id }}
      image: ${{ inputs.image_name }}
      template_bucket: ${{ inputs.template_bucket }}
      template_folder: ${{ inputs.template_folder }}

    steps:
      - name: View PR author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        run: |
          echo "ref_name=$(echo $GITHUB_HEAD_REF | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
          echo "repository_name=$(cat $GITHUB_EVENT_PATH | jq '.repository.name' | sed 's/\"//g')" >> $GITHUB_ENV
        id: set_variables

      - name: Get branch and repo names hash
        run: echo "hash_payload=$(echo $BRANCH_AND_REPO | md5sum | sed 's/  -//g')"  >> $GITHUB_ENV
        id: branch_and_repo_hash
        env:
          BRANCH_AND_REPO: "${{ env.repository_name }} ${{ env.ref_name }}"

      - name: Set project path
        run: |
          project_name=$(cat ./package.json | jq .name | sed -s 's/@mindbox-cloud\///g' | sed -s 's/-/_/g' | sed -s 's/"//g')
          if [[ $project_name == "frontend_core_v2" ]]; then
            echo "project_folder=core" >> $GITHUB_ENV
            echo "frontend_core_service=hot-testing-${{ env.hash_payload }}" >> $GITHUB_ENV
          else
            echo "project_folder=$project_name" >> $GITHUB_ENV
            echo "frontend_core_service=core-service-staging" >> $GITHUB_ENV
          fi
        id: set_project

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        timeout-minutes: 1
        continue-on-error: true
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          path: ./master-stats
          name: ${{ env.repository_name }}-master-stats
          search_artifacts: true
          check_artifacts: true
          if_no_artifact_found: warn

      - name: Rename master stats file
        run: mv ./master-stats/${{ env.project_folder }}-stats.json ./master-stats/${{ env.project_folder }}-master.json
        continue-on-error: true

      - name: Disable Lefthook
        run: echo "LEFTHOOK=0" >> $GITHUB_ENV

      # -------- BUILD -----------

      - name: Checkout frontend-deploy repository
        uses: actions/checkout@v3
        with:
          repository: mindbox-cloud/frontend-deploy
          token: ${{ secrets.frontend_gha_full_token }}
          ref: nikitin/use-fixed-build-for-testing
          path: ./deploy

      - name: read file
        run: ls ./deploy/testing-mcf-release

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node_version }}
          registry-url: "https://npm.pkg.github.com/mindbox-cloud"

      - name: Get node modules from cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: npm-ci-${{ github.sha }}

      - name: Authenticate in yandex registry
        run: echo '${{ secrets.container_registry_key }}' | docker login -u json_key --password-stdin cr.yandex

      - name: Build and format npm-package for new deploy
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
          MCF_STATIC_FOLDER: v2_static

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repository_name }}-stats
          path: |
            ./stats

      # needed for frontend discovery(build initial.js)
      - name: copy remoteEntry to v2_static folder
        run: |
          find . -type f -name "remoteEntry.js" -exec cp {} ./v2_static/ \;
        working-directory: ./build

      - name: Copy Dockerfile to build folder
        run: |
          cp ./deploy/mcf-release/Dockerfile ./build
          cp ./deploy/mcf-release/nginx.conf ./build

      - name: Build docker image
        working-directory: ./build
        run: |
          docker build . -t ${{ env.registry }}/${{ env.image }}-k8/${{ env.ref_name }}:${{ github.sha }}

      - name: Push docker image
        run: docker push ${{ env.registry }}/${{ env.image }}-k8/${{ env.ref_name }}:${{ github.sha }}

      # -------- DEPLOY HELMFILE -----------

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.1.0

      - name: Set commit hash to values
        uses: DamianReeves/write-file-action@master
        with:
          path: ./deploy/testing-mcf-release/values/hotTesting.yaml
          contents: |
            commitHash: ${{ github.sha }}
            image: ${{ env.registry }}/${{ env.image }}-k8/${{ env.ref_name }}:${{ github.sha }}
            project_folder: ${{ env.project_folder }}
            core_service_name: ${{ env.frontend_core_service }}
          write-mode: append

      - name: read file
        run: cat ./deploy/testing-mcf-release/values/hotTesting.yaml

      - name: Set HASH_PAYLOAD in helmfile
        run: |
          sed -i "s~HASH_PAYLOAD~$HASH_PAYLOAD~g" ./deploy/testing-mcf-release/helmfile.yaml
          sed -i "s~DEPLOY_TYPE~$DEPLOY_TYPE~g"  ./deploy/testing-mcf-release/helmfile.yaml
        env:
          HASH_PAYLOAD: ${{ env.hash_payload }}
          DEPLOY_TYPE: "hot-testing"

      - name: Create Helm chart
        id: create-deploy-template
        run: helmfile -f ./deploy/testing-mcf-release/helmfile.yaml -e hotTesting  template >> ./deploy.yml

      - name: print
        run: cat ./deploy.yml

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.kube_dev_config_k8 }}

      - name: Deploy to cluster
        run: helmfile sync -f ./deploy/testing-mcf-release/helmfile.yaml -e hotTesting

      - name: Slack notification if the job has completed
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
              attachments: [{
                "author_name": "Author: ${{ github.actor }}",
                fallback: 'fallback',
                color: 'good',
                title: "Repository: ${{ env.repository_name }}",
              text: "You can check your *Frontend* changes at\nhttps://hot-testing-${{ env.hash_payload }}-staging.mindbox.ru\n\nand check your PR at \nhttps://github.com/mindbox-cloud/${{ env.repository_name }}/commit/${{ github.sha }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}

      - name: Add comment to commit if the job has completed
        uses: mshick/add-pr-comment@v2
        with:
          message: ":heavy_check_mark: You can check your **Frontend** changes at\nhttps://hot-testing-${{ env.hash_payload }}-staging.mindbox.ru"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment to commit if the job has failed
        if: ${{ failure() }}
        uses: mshick/add-pr-comment@v2
        with:
          message: ":negative_squared_cross_mark: Your **Frontend** deploy failed. Check logs at\nhttps://github.com/mindbox-cloud/${{ env.repository_name }}/actions/runs/${{ github.run_id }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack notification if the job has failed
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v2
        with:
          status: custom
          payload: |
            {
              attachments: [{
                "author_name": "Author: ${{ github.actor }}",
                color: "#FF0000",
                title: "Repository: ${{ env.repository_name }}",
              text: "Your *Frontend* deploy failed. Check logs at\nhttps://github.com/mindbox-cloud/${{ env.repository_name }}/actions/runs/${{ github.run_id }}"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
