name: Phrase push
on:
  workflow_call:
    secrets:
      phraseAppToken:
        description: 'Token to access PhraseApp'
        required: true
      amixrWebhookUrl:
        description: 'Amixr webhook url to send failure alert'
        required: false
jobs:
  phrase-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      amixrWebhookUrl: ${{ secrets.amixrWebhookUrl }}

    steps:
      - uses: actions/checkout@v3

      - name: phrase push
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        continue-on-error: true
        id: phrasePushStep1
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}

      - name: wait if failed
        if: ${{ steps.phrasePushStep1.outcome == 'failure' }}
        run: sleep 60

      - name: phrase push
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        if: ${{ steps.phrasePushStep1.outcome == 'failure' }}
        continue-on-error: true
        id: phrasePushStep2
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}

      - name: wait if failed both
        if: ${{ steps.phrasePushStep1.outcome == 'failure' && steps.phrasePushStep2.outcome == 'failure' }}
        run: sleep 120

      - name: phrase push
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        if: ${{ steps.phrasePushStep1.outcome == 'failure' && steps.phrasePushStep2.outcome == 'failure' }}
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}

      - name: Amixr notification if failure
        uses: joelwmale/webhook-action@master
        if: ${{ env.amixrWebhookUrl != '' && failure() }}
        with:
          url: ${{ secrets.amixrWebhookUrl }}
          body: '{"title": "Phrase push at ${{ github.repository }} *failed*", "state": "alerting", "message": "Check logs at\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
