name: Phrase sync
on:
  workflow_call:
    inputs:
      baseBranch:
        type: string
        required: false
        default: 'master'
      allowCyrillicSymbolsInCSharpComments:
        type: boolean
        required: false
        default: false
      autoMerge:
        type: string
        description: Auto merge strategy. Posible values is github or bulldozer.
        required: false
        default: github
      commitEmail:
        type: string
        description: Email of token's user
        required: false
        default: 'action-ci@mindbox.ru'
      mergeMethod:
        type: string
        description: Method to merge. Possible values is squash or merge
        required: false
        default: merge
    secrets:
      phraseAppToken:
        description: 'Token to access PhraseApp'
        required: true
      gitHubToken:
        description: 'GitHub token used to create PRs'
        required: true
      amixrWebhookUrl:
        description: 'Amixr webhook url to send failure alert'
        required: false
jobs:
  phrase-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      amixrWebhookUrl: ${{ secrets.amixrWebhookUrl }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo chown -R root:root $GITHUB_WORKSPACE

      - name: phrase push
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}

      - name: phrase pull
        uses: mindbox-cloud/github-actions/localization/phrase-pull@master
        with:
          gitHubToken: ${{ secrets.gitHubToken }}
          commitEmail: ${{ inputs.commitEmail }}
          mergeMethod: ${{ inputs.mergeMethod }}
          phraseAppToken: ${{ secrets.phraseAppToken }}
          baseBranch: ${{ inputs.baseBranch }}
          autoMerge: ${{ inputs.autoMerge }}
          allowCyrillicSymbolsInCSharpComments: ${{ inputs.allowCyrillicSymbolsInCSharpComments }}

      - name: Amixr notification if failure
        uses: joelwmale/webhook-action@master
        if: ${{ env.amixrWebhookUrl != '' && failure() }}
        with:
          url: ${{ secrets.amixrWebhookUrl }}
          body: '{"title": "Phrase sync at ${{ github.repository }} *failed*", "state": "alerting", "message": "Check logs at\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
