name: Phrase sync
on:
  workflow_call:
    inputs:
      baseBranch:
        type: string
        required: false
        default: 'master'
      allowCyrillicSymbolsInCSharpComments:
        type: boolean
        required: false
        default: false
      autoMerge:
        type: string
        description: Auto merge strategy. The only possible value is github.
        required: false
        default: github
      commitEmail:
        type: string
        description: Email of token's user
        required: false
        default: 'action-ci@mindbox.ru'
      mergeMethod:
        type: string
        description: Method to merge. Possible values is squash or merge
        required: false
        default: merge
    secrets:
      phraseAppToken:
        description: 'Token to access PhraseApp'
        required: true
      gitHubToken:
        description: 'GitHub token used to create PRs'
        required: true
      amixrWebhookUrl:
        description: 'Amixr webhook url to send failure alert'
        required: false
jobs:
  phrase-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: false
    env:
      amixrWebhookUrl: ${{ secrets.amixrWebhookUrl }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo chown -R root:root $GITHUB_WORKSPACE

      - name: phrase push
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        continue-on-error: true
        id: phrasePushStep1
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}
      
      - name: wait if failed
        if: ${{ steps.phrasePushStep1.outcome == 'failure' }}
        uses: m3y/random-wait-action@v1
        with:
          max-wait-time: 60
      
      - name: phrase push #2
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        continue-on-error: true
        if: ${{ steps.phrasePush1.outcome == 'failure' }}
        id: phrasePushStep2
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}
     
      - name: wait if failed
        if: ${{ steps.phrasePushStep1.outcome == 'failure' && steps.phrasePushStep2.outcome == 'failure' }}
        uses: m3y/random-wait-action@v1
        with:
          max-wait-time: 120

      - name: phrase push #3
        uses: mindbox-cloud/github-actions/localization/phrase-push@master
        if: ${{ steps.phrasePushStep1.outcome == 'failure' && steps.phrasePushStep2.outcome == 'failure' }}
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}

      - name: phrase pull
        continue-on-error: true
        uses: mindbox-cloud/github-actions/localization/phrase-pull@master
        id: phrasePullStep1
        
        with:
          gitHubToken: ${{ secrets.gitHubToken }}
          commitEmail: ${{ inputs.commitEmail }}
          mergeMethod: ${{ inputs.mergeMethod }}
          phraseAppToken: ${{ secrets.phraseAppToken }}
          baseBranch: ${{ inputs.baseBranch }}
          autoMerge: ${{ inputs.autoMerge }}
          allowCyrillicSymbolsInCSharpComments: ${{ inputs.allowCyrillicSymbolsInCSharpComments }}

      - name: wait if failed
        if: ${{ steps.phrasePullStep1.outcome == 'failure' }}
        uses: m3y/random-wait-action@v1
        with:
          max-wait-time: 60
      
      - name: phrase pull #2
        continue-on-error: true
        if: ${{ steps.phrasePullStep1.outcome == 'failure' }}
        id: phrasePullStep2
        uses: mindbox-cloud/github-actions/localization/phrase-pull@master
        with:
          gitHubToken: ${{ secrets.gitHubToken }}
          commitEmail: ${{ inputs.commitEmail }}
          mergeMethod: ${{ inputs.mergeMethod }}
          phraseAppToken: ${{ secrets.phraseAppToken }}
          baseBranch: ${{ inputs.baseBranch }}
          autoMerge: ${{ inputs.autoMerge }}
          allowCyrillicSymbolsInCSharpComments: ${{ inputs.allowCyrillicSymbolsInCSharpComments }}

     
      - name: wait if failed
        if: ${{ steps.phrasePullStep1.outcome == 'failure' && steps.phrasePullStep2.outcome == 'failure' }}
        uses: m3y/random-wait-action@v1
        with:
          max-wait-time: 120

      - name: phrase pull #3
        if: ${{ steps.phrasePullStep1.outcome == 'failure' && steps.phrasePullStep2.outcome == 'failure' }}
        uses: mindbox-cloud/github-actions/localization/phrase-pull@master
        with:
          gitHubToken: ${{ secrets.gitHubToken }}
          commitEmail: ${{ inputs.commitEmail }}
          mergeMethod: ${{ inputs.mergeMethod }}
          phraseAppToken: ${{ secrets.phraseAppToken }}
          baseBranch: ${{ inputs.baseBranch }}
          autoMerge: ${{ inputs.autoMerge }}
          allowCyrillicSymbolsInCSharpComments: ${{ inputs.allowCyrillicSymbolsInCSharpComments }}

      - name: Amixr notification if failure
        uses: joelwmale/webhook-action@master
        if: ${{ env.amixrWebhookUrl != '' && failure() }}
        with:
          url: ${{ secrets.amixrWebhookUrl }}
          body: '{"title": "Phrase sync at ${{ github.repository }} *failed*", "state": "alerting", "message": "Check logs at\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
