name: Phrase push
on:
  workflow_call:
    secrets:
      phraseAppToken:
        description: 'Token to access PhraseApp'
        required: true
      slackWebhookUrl:
        description: 'Slack webhook url to send notifications'
        required: true
      amixrWebhookUrl:
        description: 'Amixr webhook url to send failure alert'
        required: false
jobs:
  phrase-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: phrase push
        uses: mindbox-moscow/github-actions/localization/phrase-push@master
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}
          slackWebhookUrl: ${{ secrets.slackWebhookUrl }}
      
      - name: Amixr notification if failure
        uses: joelwmale/webhook-action@master
        if: ${{ secrets.amixrWebhookUrl != '' && failure() }}
        with:
          url: ${{ secrets.amixrWebhookUrl }}
          body: '{"title": "Phrase push at ${{ github.repository }} *failed*", "state": "alerting", "message": "Check logs at\nhttps://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
