name: Phrase sync
on:
  workflow_call:
    secrets:
      phraseAppToken:
        description: 'Token to access PhraseApp'
        required: true
      slackWebhookUrl:
        description: 'Slack webhook url to send notifications'
        required: true
      gitHubToken:
        description: 'GitHub token used to create PRs'
        required: true
jobs:
  phrase-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: phrase push
        uses: mindbox-moscow/gha-phrase-integration@master
        with:
          phraseAppToken: ${{ secrets.phraseAppToken }}
          slackWebhookUrl: ${{ secrets.slackWebhookUrl }}

      - name: phrase pull
        uses: mindbox-moscow/gha-phrase-integration@master
        with:
          gitHubToken: ${{ secrets.frontend_gha_full_token }}
          phraseAppToken: ${{ secrets.phrase_app_token }}
